### ISSUE TITLE
'fg' must be string or integer error

### ISSUE THREAD

**Issue by Aditeya** [AlexvZyl/nordic.nvim#1]
![image](https://user-images.githubusercontent.com/22963960/213929916-279a7ea0-460e-49da-8b3a-4db9d9c1fe0d.png)

I got this error while trying to set the colorscheme.
I'm using the [lazy.nvim](https://github.com/folke/lazy.nvim)

**Comment by jemag** [comment]
can try to use PR in the meantime

**Comment by Aditeya** [comment]
Just tried it, It works well

**Comment by AlexvZyl** [comment]
Apologies!  I was out and could not respond quicker.
