### ISSUE TITLE
Cursorline option to set visual selection color

### ISSUE THREAD

**Issue by TheLastEinherjar** [AlexvZyl/nordic.nvim#100]
### I cant find an option to set the color to be used for visual selections.

___

Is the a way to set the color for visual selection, I can change the highlight group, but it would be nice to still be able to use the cursorline settings.

I think it would be better to have a option to set the bg color in cursorline which would then be used in the blend.
Instead of having a theme option.

If there is not something like that implemented and you are interested, I could make a pr for it?

**Comment by TheLastEinherjar** [comment]
heres a commit for it on my alts fork: https://github.com/5-pebbles/nordic.nvim/commit/6eca1004874050740731233d5bb22ba4e0911086

**Comment by TheLastEinherjar** [comment]
I did not mean to click that button....

**Comment by AlexvZyl** [comment]
Thanks for the commit link!  

Would you be keen to make a PR?

Just a tip, if you make PR, please only include the changes you intend to make.  I see you made a bunch of smaller changes in the linked commit :)

**Comment by 5-pebbles** [comment]
Unfortunately I think those are need for it to work, I could hardcode the color, in the defaults which would substantially cut back on changes.

But if I don't, I need to move all option related changes, to a function (extend_colors) or I get a circular import.

**Comment by 5-pebbles** [comment]
That pull request uses a hardcoded value, I will add use of the palette for default options in a different one.
