### ISSUE TITLE
Add visual preview of the colour palette

### ISSUE THREAD

**Issue by Vibhav201** [AlexvZyl/nordic.nvim#102]
Hey, thank you for this amazing theme. I just wish it had many official ports (like Catppuccin and Dracula), maybe in the future.

For now, I think there should be a colour palette preview available to view in the README.md for easy acces to the palette. This might also help others in making ports. 

So, I made one :)

![Nordic](https://github.com/AlexvZyl/nordic.nvim/assets/86820586/afe93b98-f9d1-4fb6-928d-b8aea3e9fefd)

**Comment by AlexvZyl** [comment]
Wow, thanks!

I have been wanting to add one of these for a while now.  I will make a PR at some time adding this image in the README.  Thanks!

**Comment by Vibhav201** [comment]
That's awesome. Make sure to mention this amazing project in the acknowledgment section.

https://github.com/Aonodensetsu/prev_gen

**Comment by AlexvZyl** [comment]
You can make a PR if you want?  Just link the image in this issue in the README, and put it at the end of the showcase.

**Comment by AlexvZyl** [comment]
You could actually also add the python file for if we want to regenerate it in the future.

**Comment by Vibhav201** [comment]
I was trying to avoid the hassle because I have never made a PR. I guess I need to learn how to do it somehow. I think the first step should be cloning this repo locally?

**Comment by AlexvZyl** [comment]
First time for everything!

- Fork the repo
- Clone it locally
- Make the changes
- Commit the changes with a nice message :)
- Make a PR

**Comment by Aonodensetsu** [comment]
The tool actually supports full recreation of the code from the picture itself 😎

**Comment by AlexvZyl** [comment]
> The palette tool actually supports full recreation of the code from the picture itself 😎

That's awesome :D

**Comment by Vibhav201** [comment]
You can check the PR. :)

**Comment by Vibhav201** [comment]
> _and_ comes with a cli tool that can do pretty much everything

Hey, @Aonodensetsu , can you check the issue I created in prev_gen and tell me if that can be done using the CLI tool.
