### ISSUE TITLE
Missing vim.g.colors_name

### ISSUE THREAD

**Issue by adishourya** [AlexvZyl/nordic.nvim#12]
I think you should probably add a vim.g.colors_name in your colorscheme

Expected:
```
:lua print(vim.g.colors_name)
nordic
```

Current:
```
:lua print(vim.g.colors_name)
nil
```

Other color schemes do this as well
Example:
```
:lua print(vim.g.colors_name)
catppuccin
```

**Comment by adishourya** [comment]
Awesome use of the Nord palette btw.

**Comment by AlexvZyl** [comment]
> Awesome use of the Nord palette btw.

Thanks!  It is a stunning palette.

> I think you should probably add a vim.g.colors_name in your colorscheme

Ah I missed that, thanks.
