### ISSUE TITLE
Feat: Background only in transparent mode

### ISSUE THREAD

**Issue by AlexvZyl** [AlexvZyl/nordic.nvim#126]
When enabling transparent mode, we should provide an option where only the background is transparent, and other floating windows and components are opaque.

**Comment by 5-pebbles** [comment]
I actually kind of like it with just transparent floating windows...

![27-03-24@13:55:39](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/0f50b97e-a5af-45d5-94f0-ebef140ea62d)

but it works the other way around:

![27-03-24@13:57:49](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/40ecd3cc-815d-4c1a-b40d-320b9dd3cb3f)
