### ISSUE TITLE
btop Theme

### ISSUE THREAD

**Issue by avih7531** [AlexvZyl/nordic.nvim#134]
Hi!

I see that there is a btop theme in one of the pictures in the README -- could you please share/add that? 

Thanks!

**Comment by AlexvZyl** [comment]
Hi there!  I just set my terminal colors and selected the `TTY` theme in btop.

**Comment by AlexvZyl** [comment]
Take a look [here](https://github.com/AlexvZyl/nordic.nvim/tree/main/platforms).

**Comment by AlexvZyl** [comment]
@avih7531 Please reopen if you have any other questions! :)
