### ISSUE TITLE
Change background color for selected lines with nvim-cmp

### ISSUE THREAD

**Issue by henrikig** [AlexvZyl/nordic.nvim#135]
Hi,

I can't find a way to change the background color of the selected/highlighted line in the dropdown-menu that shows up when e.g. nvim-cmp comes with completion suggestions. As of now, the color of the highlighted item is very hard to separate from the other items. Are there any settings I can use to e.g. make the background color any brighter?

![image](https://github.com/AlexvZyl/nordic.nvim/assets/47174810/31ace478-789c-4e76-a800-2c91e7b5d1dc)

**Comment by 5-pebbles** [comment]
As long as you don't have custom highlights set in your nvim-cmp config this **should** work:

```lua
require("nordic").setup({
    override = {
        Pmenu = { bg = "#CB775D" }
    }
})

```
![image](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/2f4ec67a-f820-4de1-b015-31d6a03f39b8)

**Comment by henrikig** [comment]
This works perfectly fine, thanks for the quick response!

**Comment by AlexvZyl** [comment]
> Hi,
> 
> I can't find a way to change the background color of the selected/highlighted line in the dropdown-menu that shows up when e.g. nvim-cmp comes with completion suggestions. As of now, the color of the highlighted item is very hard to separate from the other items. Are there any settings I can use to e.g. make the background color any brighter?
> 
> ![image](https://private-user-images.githubusercontent.com/47174810/333589308-31ace478-789c-4e76-a800-2c91e7b5d1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MjUwMDYsIm5iZiI6MTcxNjYyNDcwNiwicGF0aCI6Ii80NzE3NDgxMC8zMzM1ODkzMDgtMzFhY2U0NzgtNzg5Yy00ZTc2LWE4MDAtMmM5MWU3YjVkMWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA4MTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDM0MTE1YTAwOTMxYTdiNGQzZDMyMDRjOGNkOWY5NjgwNjM2N2VmOTQ0NGI5YTE4MmU3MzYxODNjM2E0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMDE3K0ekGfienMnfthYp239VCBVxj9y4UYWfE4lLWQ)

I now realize that those colors are selected based on the assumption that the user will have border chars for that menu.  Do you think we should change this @5-pebbles?

**Comment by 5-pebbles** [comment]
> I now realize that those colors are selected based on the assumption that the user will have border chars for that menu. Do you think we should change this @5-pebbles?

Yeah, we should; it's very hard to see by default. Actually, `bg_popup` is defined twice for some reason?

I personally like `bg_popup = bg_float` with `bg_selected = gray2`:
![image](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/618cf1a1-e150-4eeb-9944-9700ace8c664)
& with `swap_background = true`:
![image](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/47399f65-63e8-4e9e-99c4-23df1277676e)

> I also thing we should change the light visual selection to `gray2` but that's its own thing

**Comment by AlexvZyl** [comment]
> > I now realize that those colors are selected based on the assumption that the user will have border chars for that menu. Do you think we should change this @5-pebbles?
> 
> Yeah, we should; it's very hard to see by default. Actually, `bg_popup` is defined twice for some reason?
> 
> I personally like `bg_popup = bg_float` with `bg_selected = gray2`: ![image](https://private-user-images.githubusercontent.com/155409640/333820886-618cf1a1-e150-4eeb-9944-9700ace8c664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjE4OTcsIm5iZiI6MTcxNjcyMTU5NywicGF0aCI6Ii8xNTU0MDk2NDAvMzMzODIwODg2LTYxOGNmMWExLWUxNTAtNGVlYi05OTQ0LTk3MDBhY2U4YzY2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMTA2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTUwMDFkNTE0MTk5MWVmZjgzMTBkMWI1MmNjMWZjZGI2MzJhMjIyMTkyMDQ5M2EyOTMxODcxMDRjNTAxMTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjjWjJBbEbbXrBcUggxMJiQIiRplMa4U93WmPx-NhAA) & with `swap_background = true`: ![image](https://private-user-images.githubusercontent.com/155409640/333823433-47399f65-63e8-4e9e-99c4-23df1277676e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MjE4OTcsIm5iZiI6MTcxNjcyMTU5NywicGF0aCI6Ii8xNTU0MDk2NDAvMzMzODIzNDMzLTQ3Mzk5ZjY1LTYzZTgtNGU5ZS05OWM0LTIzZGYxMjc3Njc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMTA2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGVkYzEwNzkyMjk1YjAyY2JkOWQwZWUyYWQ4ZjU4ZDI1MDE5ZmE2MGIxMDNkZjMwY2QwZDRiODc2MGFkMDg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9A-l0d5Cerko75fKWcguiPnNXeZQ0LbX70QLj8kLxLk)
> 
> > I also think we should change the light visual selection to `gray2` but that's its own thing.

Yeah that looks good!

**Comment by RossBarnie** [comment]
I've been trying this on the dev branch and the colours are the same as reported by OP.

Lazy config:
```lua
    'AlexvZyl/nordic.nvim',
    lazy = false,
    priority = 1000,
    branch = "dev",
    config = function()
      require('nordic').load({
        on_highlight = function(highlights, palette)
          highlights.NeoTreeGitUntracked = { fg = palette.magenta.dim } -- this is fine
        end
      })
    end
```

I've tried adding
```lua
highlights.Pmenu = { bg = "#ffffff" }
```
to the `on_highlight` function but it doesn't change anything.

**Comment by 5-pebbles** [comment]
> I've been trying this on the dev branch and the colours are the same as reported by OP.
> 
> Lazy config:
> 
> ```lua
>     'AlexvZyl/nordic.nvim',
>     lazy = false,
>     priority = 1000,
>     branch = "dev",
>     config = function()
>       require('nordic').load({
>         on_highlight = function(highlights, palette)
>           highlights.NeoTreeGitUntracked = { fg = palette.magenta.dim } -- this is fine
>         end
>       })
>     end
> ```
> 
> I've tried adding
> 
> ```lua
> highlights.Pmenu = { bg = "#ffffff" }
> ```
> 
> to the `on_highlight` function but it doesn't change anything.

I can't reproduce your issue:
```lua
'AlexvZyl/nordic.nvim',
lazy = false,
priority = 1000,
branch = "dev",
config = function()
    require('nordic').load({
        on_highlight = function(highlights, palette)
            highlights.Pmenu = { bg = "#ffffff" }
        end
    })
end
```
![image](https://github.com/AlexvZyl/nordic.nvim/assets/155409640/b25b6b37-3d4d-49a5-9b1d-35c04f8cb96e)

I would guess, however, that your nvim-cmp config is using a different highlight (not `Pmenu`).

Could you share that config?

**Comment by RossBarnie** [comment]
Ignore me, you were absolutely right I had highlight overrides that I completely forgot about in nvim-cmp which explains my issue!
