### ISSUE TITLE
Request for feature: disable italics for everything/anything

### ISSUE THREAD

**Issue by TympanicLemon** [AlexvZyl/nordic.nvim#136]
Title basically, i currently have certain keywords or parameters used in functions, stuff like that italicized and I would love to have an option to disabled that since personally I prefer to have NOTHING throughout my code italicized!

Screenshot is an example, where `opts` is italicized but I really hope this is an easy fix.

![Screenshot 2024-05-24 at 7 27 17 PM](https://github.com/AlexvZyl/nordic.nvim/assets/134819373/d2f5f091-fd01-4908-a9b5-34e5104efc47)

**Comment by 5-pebbles** [comment]
As far as I can tell there is no easy way of doing this on `main` for now...

#124 should allow something like this:
```lua
require('nordic').setup {
    -- This callback can be used to override highlights before they are applied.
    on_highlight = function(highlights, _palette)
        for _, highlight in pairs(highlights) do
            highlight.italic = false
        end

        return highlights
    end
}
```

If you would like you can use that branch, but I have no idea if/when that will be merged with `main`.

> **Note:** While I don't have the final say in the matter I expect we will not be adding a separate option for this.

**Comment by AlexvZyl** [comment]
Yeah I completely understand not wanting italics.  We can add an option for this, what do you think @5-pebbles?

**Comment by 5-pebbles** [comment]
> Yeah I completely understand not wanting italics. We can add an option for this, what do you think @5-pebbles?

Well, they are only used in `11` places, so it would be easy to do; however, in general, I think we should avoid adding too many options.


I feel like it falls into the same category as #100, with a general solution being better.

If we are going to add it, how should it interact with `italic_comments`? It would only take a few minutes to create a pr...

**Comment by AlexvZyl** [comment]
Actually, on the note of not having too many options @5-pebbles, terminal emulators usually allow disabling italics.  Removes some responsibility from nordic.

@TympanicLemon What terminal emulator do you use?

**Comment by TympanicLemon** [comment]
@AlexvZyl Oh I didn't even know that was a thing terminals could do, I am currently using ghostty

**Comment by TympanicLemon** [comment]
Also sorry I didn't see these earlier everyone, I just woke up about 30 minutes ago, its 6:30am for me over here in California, USA!

**Comment by TympanicLemon** [comment]
@AlexvZyl So, I was able to disable it (can't believe I didn't think of this earlier tbh so thank you so much!)
Here is the line in case anyone else with this problem comes up, just plopped that in my config file for ghostty and problem solved :)

font-style-italic = false

**Comment by AlexvZyl** [comment]
> @AlexvZyl So, I was able to disable it (can't believe I didn't think of this earlier tbh so thank you so much!) Here is the line in case anyone else with this problem comes up, just plopped that in my config file for ghostty and problem solved :)
> 
> font-style-italic = false

Great!
