### ISSUE TITLE
Helix Theme

### ISSUE THREAD

**Issue by 5-pebbles** [AlexvZyl/nordic.nvim#148]
@AlexvZyl I am finishing up a Nordic theme for Helix; however, it is not an exact replica of the Neovim one. Helix themes don't support configuration options, so I changed a few things around for better defaults.

As such, I think it might need its own readme like doc, so should I merge it here or make a separate repo for it?

**Comment by 5-pebbles** [comment]
I made it a seprate repository: [nordic-helix ](https://github.com/5-pebbles/nordic-helix). There are quite a few subtle differences between the two, and I think this will make it easier to find when searching for helix themes.

**Comment by AlexvZyl** [comment]
Sorry for being away, me and my wife moved.  

Also, I am going away on vacation until 16 July, so will only be able to review everything after that.  You are obviously welcome to manage issues etc if you want to.

See you then!

**Comment by 5-pebbles** [comment]
> Sorry for being away, me and my wife moved.
> 
> Also, I am going away on vacation until 16 July, so will only be able to review everything after that. You are obviously welcome to manage issues etc if you want to.
> 
> See you then!

Have fun!!!!
