### ISSUE TITLE
Weird highlighting for neo-tree

### ISSUE THREAD

**Issue by Leonard-Pat** [AlexvZyl/nordic.nvim#151]
<img width="777" alt="Screenshot 2024-07-14 at 22 01 17" src="https://github.com/user-attachments/assets/f1be0c5a-59e2-4433-a994-635a53d54cdc">
Im getting this weird highlighting behaviour for neo tree (both floating window and non floating)

**Comment by 5-pebbles** [comment]
I will look into this some time this week... but first I need some more details (I don't use neo-tree).

I am assuming you mean the selected text bg not being highlighted?

![image](https://github.com/user-attachments/assets/a835ddbb-b314-48b5-8b76-8cc3d34b25fd)

If not that, what's the weird highlight?

Also, is the issue new or has it been like that long as you have been using it?

**Comment by Leonard-Pat** [comment]
Hi thanks for the quick response! yes correct, theres some strange interaction with text not being highlighted, however if the text has a different colour it doesnt happen
<img width="785" alt="Screenshot 2024-07-15 at 10 51 13" src="https://github.com/user-attachments/assets/fc94582e-c289-45eb-9161-415e0faa9799">

**Comment by 5-pebbles** [comment]
It should be fixed on the `neotree_highlights` branch in #152 which will be merged into `dev` and then `main` with the next release.

Thanks for the report ;)

**Comment by Leonard-Pat** [comment]
amazing thanks !

**Comment by AlexvZyl** [comment]
Apologies for delaying.  Should be fixed in the new release #144.

**Comment by bini-x** [comment]
has it been fixed yet?

**Comment by AlexvZyl** [comment]
Dev got merged :)
