### ISSUE TITLE
Console keyword color is getting overwritten or something

### ISSUE THREAD

**Issue by bini-x** [AlexvZyl/nordic.nvim#159]
[Screencast from 09-28-2024 04:00:40 PM.webm](https://github.com/user-attachments/assets/2c0eaaa5-cb24-41a4-b012-dfea8d7b1d0a)

**Comment by bini-x** [comment]
I tried changing the "builtin" highlight group color, but it did the same (showed the color first and then went back to white as shown in video).

**Comment by AlexvZyl** [comment]
Hover the console keyword and do `:TSHighlightCapturesUnderCursor`.

**Comment by bini-x** [comment]
This command is not working, I tried installing "playground" but it's not showing it

**Comment by bini-x** [comment]
wait it does now

**Comment by AlexvZyl** [comment]
Ohja, I forgot to mention you need that extension...

**Comment by bini-x** [comment]
![image](https://github.com/user-attachments/assets/293802b7-1b1b-43aa-8090-3bdf8e258c80)
got Playground for treesiter, typed :TSEditQuery (because the tshighlight.... wasn't showing), closed it and now even the log() is not colorized lol. I don't think I ever changed something, idk why it's behaving like this now

**Comment by AlexvZyl** [comment]
Do:

```
:TSInstall javascript
:TSUpdateSync
```

Does it still give the issue?

**Comment by bini-x** [comment]
Yeah still the same

**Comment by bini-x** [comment]
![image](https://github.com/user-attachments/assets/54e43a7d-7e89-4da0-afff-b8afb3bb83f2)
this is the config

**Comment by AlexvZyl** [comment]
And `:LspInfo`?

**Comment by bini-x** [comment]
![image](https://github.com/user-attachments/assets/35c10385-df9a-468e-bcca-28331246b34a)

**Comment by AlexvZyl** [comment]
No when you are inside the javascript file.

**Comment by bini-x** [comment]
![image](https://github.com/user-attachments/assets/297e68fe-bc04-45fc-8e42-b3f1f62d07e4)

**Comment by AlexvZyl** [comment]
I think the lsp overrides the highlight.  In my editor I get the same as you but when I stop the LSP the hl is correct.

**Comment by AlexvZyl** [comment]
Not the first time I have seen this and not really sure how to handle it.

**Comment by AlexvZyl** [comment]
If you find a solution let me know :)

**Comment by bini-x** [comment]
maybe a dumb question but I upgraded to node 22.9.0 and npm 10.8.3 yesterday. Can that be the case?

**Comment by AlexvZyl** [comment]
I think that is unlikely, the LSP is a separate binary.

**Comment by AlexvZyl** [comment]
Take a look here:   https://github.com/NvChad/NvChad/issues/1907

**Comment by AlexvZyl** [comment]
Try this: 
```lua
vim.highlight.priorities.semantic_tokens = 94
```

**Comment by bini-x** [comment]
In lsp config right?

**Comment by AlexvZyl** [comment]
Anywhere in a lua file that gets loaded.

**Comment by bini-x** [comment]
Yeah this did the trick!
Thank you so much Alex for all the help these days.
Also a note for someone who might have this problem: I also disabled "playground" of treesitter.

**Comment by AlexvZyl** [comment]
No problem!
