### ISSUE TITLE
Allow disabling italics in comments

### ISSUE THREAD

**Issue by NTBBloodbath** [AlexvZyl/nordic.nvim#17]
Hey, hope you're doing well!

I'm really loving this colorscheme, I'm not really a Nord fan but this variant looks really cool, nice job!

The only thing I would like is to be able to disable the italics in some hl groups like `Comment` from the `setup` function so that I don't have to add extra code in my setup to `gui=NONE` that hl group, would it be possible? :p

Cheers

**Comment by AlexvZyl** [comment]
Hi there!  Thanks :)

Yes, I will most definitely add some proper configuration.
