### ISSUE TITLE
Text unreadable/unusable with diffing plugins

### ISSUE THREAD

**Issue by kuntau** [AlexvZyl/nordic.nvim#3]
Pretty much unusable with `neogit` & `diffview`

<img width="1486" alt="Screenshot 2023-01-23 at 3 32 52 AM" src="https://user-images.githubusercontent.com/327489/213940135-f9577d90-83cd-44ed-b9da-33e88d0d449d.png">
<img width="733" alt="Screenshot 2023-01-23 at 3 36 54 AM" src="https://user-images.githubusercontent.com/327489/213940142-a3e7a1fb-0624-4668-8235-454f3628da65.png">

**Comment by AlexvZyl** [comment]
Yeah I thought this might have been wrong, have not gotten the chance to check the diff colors.  Thanks for opening the issue.
