### ISSUE TITLE
Low legibility for code in help

### ISSUE THREAD

**Issue by kuntau** [AlexvZyl/nordic.nvim#39]
Nordic use same color as `comment` for code in help make them very hard to read. Majority of other theme use `string` color. See screenshot

### Nordic
![Screen Shot 2023-02-05 at 23 36 42](https://user-images.githubusercontent.com/327489/216829086-f30482ca-7c95-4923-bd78-52f208aa8544.png)

### Tokyonight
![Screen Shot 2023-02-05 at 23 37 05](https://user-images.githubusercontent.com/327489/216829104-c3ef9c5c-03a1-4726-9aa5-c456df85d96e.png)

**Comment by AlexvZyl** [comment]
Thanks, will fix!

**Comment by AlexvZyl** [comment]
What highlight is used there?

**Comment by AlexvZyl** [comment]
It is `@text.literal`.
