### ISSUE TITLE
Suggestion: don't set LeapBackdrop in default

### ISSUE THREAD

**Issue by kuntau** [AlexvZyl/nordic.nvim#41]
I think user should opt-in to use this old style like the `lightspeed`. Personally it break my flow with it enabled.

And I think the previous yellow `#D9B263` is better than this new red.

**Comment by AlexvZyl** [comment]
Agreed, will add the backdrop as an option in the configs.

Did you like it more when the `bg` was set to the color instead of the `fg`?

**Comment by AlexvZyl** [comment]
I went ahead and just reverted it to the old style.  Let me know if you meant something elese.

**Comment by kuntau** [comment]
Perfect. Yeah, I prefer to have `bg`, easier to see but not too distracting
