### ISSUE TITLE
[ENH] transparent background for popups (telescope, mason...)

### ISSUE THREAD

**Issue by baggiponte** [AlexvZyl/nordic.nvim#48]
Congrats for the theme, colors are awesome and the setup straightforward (I am mostly using gruvbox-material, which is vimscript so a little less straightforward to use). However, I was expecting that the transparency option would make popup windows bg transparent as well. I am no colorscheme expert, but I'd be glad to help!

**Comment by AlexvZyl** [comment]
Glad you like it!  

I agree with you, should definitely add an option to do that.  The only possible issue I am aware of, is that some of the plugins (for example, lspsaga.nvim) handle window transparency separately from the  the Neovim settings.  But I do not have a problem with extending support to handle the plugins.

The work has slightly slowed down, since I am grinding to get my thesis submitted.  But after that I am going to add some stuff, including this.

**Comment by baggiponte** [comment]
I will have a look around and try to find a solution 💪🏼

**Comment by AlexvZyl** [comment]
I think this might be fixed with #97...

**Comment by baggiponte** [comment]
Will try it soon!

**Comment by AlexvZyl** [comment]
You should be able to set the branch you use with your plugin manager.  Currently it is on `dev`.  Should be merged in relatively soon though.

**Comment by AlexvZyl** [comment]
I think my latest merge fixed this, but I am not sure.  Please let me know if this is still an issue.

**Comment by baggiponte** [comment]
Hey there! Will check when I have time later this week. Thanks for pinging me :)

**Comment by baggiponte** [comment]
Hey there, tried running `colorscheme nordic` with the latest commit from the main branch and got this error:

```
11:38:07 msg_show   colorscheme nordic E5108: Error executing lua .../.local/share/nvim/lazy/nordic.nvim/lua/nordic/utils.lua:114: attempt to perform arithmetic on local 'c_fg' (a nil value)
stack traceback:
	.../.local/share/nvim/lazy/nordic.nvim/lua/nordic/utils.lua:114: in function 'blend_channel'
	.../.local/share/nvim/lazy/nordic.nvim/lua/nordic/utils.lua:118: in function 'blend'
	...l/share/nvim/lazy/nordic.nvim/lua/nordic/colors/init.lua:32: in function 'extend_palette'
	...a/.local/share/nvim/lazy/nordic.nvim/lua/nordic/init.lua:17: in function 'load'
	[string ":lua"]:1: in main chunk
```

**Comment by AlexvZyl** [comment]
That is odd.  Can you show me your setup (if any) and package manager config?

**Comment by 5-pebbles** [comment]
I think this is the same thing I am running in to:
```lua
    C.bg = (O.transparent_bg and C.none) or C.gray0
    C.bg_dark = (O.transparent_bg and C.none) or C.black0
    C.bg_highlight = U.blend(C.bg_dark, C.bg, O.cursorline.blend) -- Line 32 colors init
```

Its trying to blend, 'NONE' which is not a hex value.
However, I nor GitHub actions get an error unless I change the default value of transparent_bg to true.

I don't know why [baggiponte](https://github.com/baggiponte) would be getting this.

If this is a bug I can make a pr and fix it, by making blend handle none or just skipping the blending function if none is used.

the error I get is:
```txt
Failed to run `config` for nordic

...El/.config/nvim/git/bin/nordic.nvim/lua/nordic/utils.lua:114: attempt to perform arithmetic on local 'c_fg' (a nil value)

# stacktrace:
  - git/bin/nordic.nvim/lua/nordic/utils.lua:114 _in_ **blend_channel**
  - git/bin/nordic.nvim/lua/nordic/utils.lua:118 _in_ **blend**
  - git/bin/nordic.nvim/lua/nordic/colors/init.lua:33 _in_ **extend_palette**
  - git/bin/nordic.nvim/lua/nordic/init.lua:17 _in_ **load**
  - lua/core/lazy.lua:61 _in_ **config**
  - lua/core/lazy.lua:305
  - lua/core/init.lua:4
  - init.lua:1
  ```

**Comment by AlexvZyl** [comment]
Oh, yeah, I am blending a 'none' value.  Oops.

We can just have the blend function return none when we try and blend a none value.

**Comment by AlexvZyl** [comment]
Thanks for finding the bug @5-pebbles! :)

**Comment by AlexvZyl** [comment]
This should have been caught in the tests.  We need to cover it.

**Comment by AlexvZyl** [comment]
I just went ahead and fixed it, I don't want people's neovim breaking because of a colorscheme.

**Comment by baggiponte** [comment]
Error fixed! About the transparency:

![image](https://github.com/AlexvZyl/nordic.nvim/assets/57922983/fc130c1c-204e-4289-acdd-c30a41730a30)

There's something off with the borders. Mason and Lazy popup are not transparent too. How can I help you with this?

**Comment by AlexvZyl** [comment]
Ah, makes sense.  Will fix this on Sunday.

**Comment by baggiponte** [comment]
Another very minor thing: the pane separator is black and the NvimTree separator is white. Could they be made the same? Another unrequested opinion: with transparency, using black as a line separator feels weird. How can I change it to idk gray? Thanks :)

**Comment by 5-pebbles** [comment]
For the blend, I will make a pr to just uses the non-none color.
and then I will revert https://github.com/5-pebbles/nordic.nvim/commit/ea86462fa8fdeab9037300b7236e6e01f2d048ff for #101

**Comment by AlexvZyl** [comment]
> Another very minor thing: the pane separator is black and the NvimTree separator is white. Could they be made the same? Another unrequested opinion: with transparency, using black as a line separator feels weird. How can I change it to idk gray? Thanks :)

All valid concerns.  Just thought about the black separator...

**Comment by AlexvZyl** [comment]
Also, could you check on the `dev` branch if your border issue is resolved?

**Comment by baggiponte** [comment]
> Can you please open a new issue?

Ops sorry completely missed that. will do.

> Also, could you check on the dev branch if your border issue is resolved?

It seems something changed indeed. The color's still dark (should be gray or white or the same as the highlight used by noice?) but at least it's not the "rectangle" it was before.

![image](https://github.com/AlexvZyl/nordic.nvim/assets/57922983/f06f5fcd-1d38-4403-aa8b-ccd5076f1045)

**Comment by AlexvZyl** [comment]
Enable bright borders and see if that is what you want?  Share a screenshot, I am curious.

**Comment by baggiponte** [comment]
Uuh didn't see that in the readme, that looks great! :) 

<img width="1239" alt="image" src="https://github.com/AlexvZyl/nordic.nvim/assets/57922983/a6ff2fcf-83a7-4722-933d-4402162a0766">

**Comment by baggiponte** [comment]
Unrelated: do you know what highlights I can change to have a rounded border around this completion menu? It should be nvim-cmp's cmdline source. It does not work with my other theme of choice, gruvbox-material:

nordic
<img width="241" alt="image" src="https://github.com/AlexvZyl/nordic.nvim/assets/57922983/ee0a69c5-3933-4e53-877d-7c79d6a906fc">

gruvbox-material

Unrelated: do you know what highlights I can change to have a rounded border around this completion menu? It should be 

<img width="241" alt="image" src="https://github.com/AlexvZyl/nordic.nvim/assets/57922983/ee0a69c5-3933-4e53-877d-7c79d6a906fc">

**Comment by AlexvZyl** [comment]
This should help you out :)

https://github.com/AlexvZyl/nvim/blob/main/lua%2Falex%2Flang%2Fcompletion%2Fcmdline.lua
