### ISSUE TITLE
Colorscheme is completly white and need to be switched back to work

### ISSUE THREAD

**Issue by Carbone13** [AlexvZyl/nordic.nvim#50]
Installed the theme with vim-plug, called `colorscheme nordic` and everything is plain white
Installed another theme, and switching to the new one, then setting back Nordic make the theme work
Like that : 
`colorscheme tokyonight
colorscheme nordic`

**Comment by AlexvZyl** [comment]
Thank you for opening the issue.  I am not 100% sure why this occurs, but my guess is that it must have something to do with setting up colorschemes with vim-plug.  I do not have the time to look into it right now, but i will as soos as I have some spare time.

**Comment by mactep** [comment]
Add `vim.o.termguicolors = true` before loading the colorscheme in your `init.lua` or `set termguicolors` in your `init.vim`.

**Comment by AlexvZyl** [comment]
Thanks @mactep!  @Carbone13, can you please check if that fixes it?

**Comment by Carbone13** [comment]
I can confirm that `set termguicolors` fix the issue !
