### ISSUE TITLE
make visual selection easy to see

### ISSUE THREAD

**Issue by effinsky** [AlexvZyl/nordic.nvim#61]
currenty visual selection is really hard to distinguish from general background. would be good to have it be a lighter color, so it contrasts with the backround more:

<img width="738" alt="Screenshot 2023-04-09 at 17 54 52" src="https://user-images.githubusercontent.com/54535543/230783180-3fc3d4d0-f9a3-45fd-a530-77f7b783c609.png">

i'm sure one can configure it but I'm opening this issue in the name of having defaults be as good as they possibly can. thanks in advance.

**Comment by AlexvZyl** [comment]
Yes, it is quite dim, but that was intentional and just my personal preference.

The color is a blended version of some two of the existing colors (a gray and the background) and I can easily expose the blend ratio as a number in the config options.

**Comment by effinsky** [comment]
sure, or just a visual selection color exposed in the config as an absolute hex value. whatever you think best. thanks!

**Comment by AlexvZyl** [comment]
You can already easily override it with:
```lua
require 'nordic' .setup {
    override = {
        CursorLine = {
            bg = '#000000',  -- Choose a color you like.
            bold = true -- Or false.
        },
        Visual = {
            bg = '#000000',  -- Choose a color you like.
            bold = true -- Or false.
        }
    }
}
```
