### ISSUE TITLE
Invalid Character In GroupName

### ISSUE THREAD

**Issue by jaustinj** [AlexvZyl/nordic.nvim#63]
I have the same error that is seen here on shaunsingh/nord.nvim.

Package does not seem to work with nvim <0.7 and packer, but upgrading to nvim >0.7 started getting this issue. 

<img width="236" alt="image" src="https://github.com/AlexvZyl/nordic.nvim/assets/33203110/6ff9d5e0-3ef7-49f3-ad0f-d0bd8466f980">

https://github.com/shaunsingh/nord.nvim/issues/113

**Comment by jaustinj** [comment]
Was able to resolve by upgrading to neovim >0.8

**Comment by AlexvZyl** [comment]
Cool, thanks for the issue.

**Comment by AlexvZyl** [comment]
Thanks for the heads-up, but I do not plan om maintaining old versions of neovim.
