### ISSUE TITLE
[suggestion] Make the focus buffer bg different than the nonfocus on so to easy differentiate which one is the main buffer in multi buffer window 

### ISSUE THREAD

**Issue by i3d** [AlexvZyl/nordic.nvim#65]
Looks like so far all buffers are using the same bg. I did a bit hack override to use a little darker bg and it turns out wonderful side effect is that the nonfocused ones are still in the lighter one but the focused is now using my override which is immediately helpful in identifying which one I am editing.

**Comment by AlexvZyl** [comment]
Initially I though this might be out of scope, but I see tokyonight has it.  I am more than happy to add it, unless you are keen to make a PR?

**Comment by AlexvZyl** [comment]
You are welcome to re-open.
