### ISSUE TITLE
Visual selection regression: not enough contrast between selected / non-selected background 

### ISSUE THREAD

**Issue by lynndylanhurley** [AlexvZyl/nordic.nvim#68]
I just pulled the latest a couple of days ago, and it looks like the visual selection background color has been updated to darken the background, whereas it used to lighten the background.

I feel like there's no longer enough contrast to see the difference between selected / non-selected text.

This also causes problems when I'm sharing my screen for zoom calls, because the video compression reduces the contrast even further so no one can tell what I have selected.

Screenshot of how it looks now:

<img width="440" alt="Screenshot 2023-07-08 at 3 40 51 PM" src="https://github.com/AlexvZyl/nordic.nvim/assets/468037/ab7e897b-38e3-4f8d-baef-a758b75fd2d3">

**Comment by lynndylanhurley** [comment]
Found the override. If anyone else is having this issue, I was able to resolve with this config:

```lua
    local c = require('nordic.colors')

    require('nordic').load({
      override = {
        Visual = {
          bg = c.gray1,
          bold = true
        }
      }
    })
```

Looks like this:

<img width="396" alt="Screenshot 2023-07-08 at 3 50 43 PM" src="https://github.com/AlexvZyl/nordic.nvim/assets/468037/4dcd0c41-96e2-4e3f-a5f4-86e51663d2de">

**Comment by lellingsen** [comment]
@lynndylanhurley thank you for the override, very helpful!
