### ISSUE TITLE
TS Context poor colors

### ISSUE THREAD

**Issue by I-Own-You** [AlexvZyl/nordic.nvim#77]
<h1> Hello </h1>

<h3> The treesitter context is making the line literally impossible to read, also when i go in insert mode, it anyway stays the same.</h3>

![Screenshot from 2023-07-29 22-36-09](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/dd9ca083-24d4-4ad7-a884-bdcc5a0e987c)

![Screenshot from 2023-07-29 22-37-21](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/5429878b-81e3-459c-b90f-e39dfe13fad3)

<h4>Is there a way to disable it?</h4>
<br><h4>Or make something like an underline like this, without changing anything but underline ? </h4>

![Screenshot from 2023-07-29 22-44-50](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/e7b9717f-055b-40a5-b3ef-4782f1de65f7)

**Comment by AlexvZyl** [comment]
Maybe try:

```lua
require 'nordic' .setup {
    ts_context = { dark_background = false }
}
```

**Comment by AlexvZyl** [comment]
I don's use TS context, but I agree the underline looks quite nice.

**Comment by AlexvZyl** [comment]
You can submit a PR if you want?  Colors are defined here https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/nordic/groups/integrations/treesitter-context.lua.

**Comment by I-Own-You** [comment]
> Maybe try:
> 
> ```lua
> require 'nordic' .setup {
>     ts_context = { dark_background = false }
> }
> ```

didnt work

**Comment by I-Own-You** [comment]
> You can submit a PR if you want? Colors are defined here https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/nordic/groups/integrations/treesitter-context.lua.

i will try

**Comment by I-Own-You** [comment]
So it appears that it wasnt the _**nvim-ts-context**_.

It was the [indent-blank_line plugin](https://github.com/lukas-reineke/indent-blankline.nvim) that is responsible for underline of the context.
The [vim-matchup](https://github.com/andymass/vim-matchup) for the bg of the matching context.

So, for [indent-blank_line plugin](https://github.com/lukas-reineke/indent-blankline.nvim), that is responsilbe for the underline, the highilight group would be:

```lua
    IndentBlanklineContextStart = {
      underline = true, sp='#8FBCBB', nocombine = true
    },
```
It didnt work for me to override it, though. But as a workaround i added it as vim command, and it works, you can put it in config function when loading the plugin or in setup options of the plugin:

```lua
      vim.cmd([[highlight IndentBlanklineContextStart guisp=#8FBCBB gui=underline]])
```

The workaround for the [vim-matchup](https://github.com/andymass/vim-matchup), that is responsilbe for bg,fg, .etc for the context matchup, would be aswell in vim command, because the highlight group also didnt work:

```lua
      vim.cmd([[highlight MatchParen guibg=#5C4E4E]])   -- for the bg
      vim.cmd([[highlight MatchParen gui=NONE]])   -- no underline
```
<br/>

This is how it can be setup with [lazy.nvim](https://github.com/folke/lazy.nvim):
![Screenshot from 2023-07-30 12-11-48](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/df1ae435-63f3-4c5f-9a94-394115b0d49b)
![Screenshot from 2023-07-30 12-12-10](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/1e025d76-3193-4030-922f-e0fd0ccd3598)
<br/>
And the final result would look like this:
![Screenshot from 2023-07-30 12-17-28](https://github.com/AlexvZyl/nordic.nvim/assets/91146968/efc59ddb-6931-404d-a8a9-0be7f305fe3e)

<br/>

**_Feel free to change the colors._**

**Comment by AlexvZyl** [comment]
I see, thanks for checking!  I don't like `indent-blankline`'s context, but I will add an option to enable it.

**Comment by AlexvZyl** [comment]
I still want to implemenet this :)

**Comment by AlexvZyl** [comment]
Sorry about that, was actually a super simple mistake on my side.
