### ISSUE TITLE
Invalid color display with bordered telescope

### ISSUE THREAD

**Issue by K1nGsmaN-hub** [AlexvZyl/nordic.nvim#8]
<img width="1440" alt="Снимок экрана 2023-01-23 в 08 21 49" src="https://user-images.githubusercontent.com/61147301/213948543-e47d0d89-e492-45f5-b5fd-04f9a0d8a524.png">

**Comment by AlexvZyl** [comment]
This is intended behaviour.  I do not want to hide border using the colroscheme.

Top achieve the look in the screnshot, you can do:

```lua
local border_chars_none = { " ", " ", " ", " ", " ", " ", " ", " " }
require 'telescope' .setup {
    defaults = {
        borderchars = {
            prompt = border_chars_none,
            results = border_chars_none,
            preview = border_chars_none,
        }
    }
}
```

Though, I do think it does not look good.  I think I should add styles for `telescope`.

**Comment by AlexvZyl** [comment]
Please see the README for updated information!
