### ISSUE TITLE
Nordic theme for helix editor

### ISSUE THREAD

**Issue by artemst** [AlexvZyl/nordic.nvim#92]
Hello, thank you for such great theme! 
I used it in vim, but now I switched to [helix editor](https://helix-editor.com/) and I would love to use nordic there too.
Do you have plans for migrating theme for helix?

**Comment by AlexvZyl** [comment]
Hi there!  Glad you like the theme :)

I do not use the helix editor myself, nor do I plan on switching to it.  Though, it seems a lot easier to create a theme for helix than for neovim, so you are welcome to try and make a PR?  All of the colors I use are defined [here](https://github.com/AlexvZyl/nordic.nvim/blob/main/lua/nordic/colors/nordic.lua).

**Comment by AlexvZyl** [comment]
See [this implementation](https://github.com/CptPotato/helix-themes/blob/main/schemes/everforest) and [this palette file](https://github.com/CptPotato/helix-themes/blob/main/palettes/everforest/dark_hard).

**Comment by AlexvZyl** [comment]
Any updates?  If you are not planning on doing this anymore, please close the issue :)

**Comment by AlexvZyl** [comment]
Please reopen this issue if you have questions or plan on implementing this :)
