### ISSUE TITLE
Overriding the visual  selection

### ISSUE THREAD

**Issue by skimask9** [AlexvZyl/nordic.nvim#98]
![Screenshot 2023-10-19 024815](https://github.com/AlexvZyl/nordic.nvim/assets/88349133/156fe91c-18bb-4ea6-8d7c-a7f307d806f0)
![Screenshot 2023-10-19 024701](https://github.com/AlexvZyl/nordic.nvim/assets/88349133/71f1b455-c4fe-464b-b5e4-1da0ce9c3d64)
![Screenshot 2023-10-19 024853](https://github.com/AlexvZyl/nordic.nvim/assets/88349133/d6f2aa30-f973-430d-95b2-36ba39fc134f)

**Comment by AlexvZyl** [comment]
Thanks for the report.

Interesting.  What is the output of `nvim --version`?

**Comment by skimask9** [comment]
> Thanks for the report.
> 
> Interesting. What is the output of `nvim --version`?

NVIM v0.8.0

**Comment by AlexvZyl** [comment]
Apologies for disappearing.  Can you confirm that this is still an issue?

**Comment by AlexvZyl** [comment]
IMO this is a not an issue with nordic.  They should supply defaults with their plugin.

**Comment by AlexvZyl** [comment]
Please reopen if you believe I am wrong :)
