### ISSUE TITLE
Change NeoTreeGitAdded

### ISSUE THREAD

**Issue by olejech** [AlexvZyl/nordic.nvim#99]
Hi, thanks for great color scheme!

I'm trying to change NeoTreeGitAdded.

```lua
local palette = require 'nordic.colors'

require 'nordic'.setup({
  cursorline = {
    theme = 'light'
  },
  override = {
    NeoTreeGitModified = {
      fg = palette.orange.base, -- works perfect
    },
    NeoTreeGitAdded = {
      fg = palette.orange.base, -- not working
    },
  },
  on_palette = function(nordicPalette)
    nordicPalette.git.add = '#FFFFFF' -- not working
    return nordicPalette
  end,
})

vim.cmd("colorscheme nordic")
```

How I can to change color?

It's looks like this:

<img width="717" alt="Снимок экрана 2023-11-14 в 09 00 34" src="https://github.com/AlexvZyl/nordic.nvim/assets/64708593/b733672c-7ce5-406e-b6fb-2c2850350095">

**Comment by AlexvZyl** [comment]
That is odd.  I will look into it after the 7th of Jan :)

**Comment by RossBarnie** [comment]
FYI I've just changed this myself as I find the Unstaged color too dim but didn't find any issues with using the `override` syntax as OP was doing.

Neovim 0.9.5

Working config:

```lua
      local palette = require('nordic.colors')
      require('nordic').setup {
        override = {
          NeoTreeGitUntracked = { fg = palette.magenta.dim },
          NeoTreeGitAdded = { fg = palette.orange.base }
        }
      }
```
![image](https://github.com/AlexvZyl/nordic.nvim/assets/2567153/9c523aaf-7a74-4197-b4c5-567712ec12e4)

**Comment by AlexvZyl** [comment]
I think #113 fixes this.
